config/routes.rb
Rails.application.routes.draw do
	resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def show
		@artist = Artist.find(params[:id])
	end

	def create
		@artist = Artist.create(artist_params)
		redirect_to @artist
	end

	def update
		@artist = Artist.find(params[:id])
		@artist.update(artist_params)
		redirect_to artist_path(@artist)
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def destroy
		@artist = Artist.find(params[:id])
		@artist.destroy
		redirect_to artists_path
	end

	private

	def artist_params
		params.require(:artist).permit(:name, :image_path)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<h1>Edit an Article</h1>

<%= form_for(@artist) do |f| %>
	<p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :image_path %><br />
    <%= f.text_area :image_path %>
	</br>
		<%= f.submit %>
  </p>

	<% end %>

app/views/artists/index.html.erb
<h1>Artists:</h1>
<%= link_to "New artist", new_artist_path %> <br/> <br/>
	<% @artists.each do |artist| %>
		<%= link_to artist.name, artist_path(artist) %> </br>
		<%= link_to "edit", edit_artist_path(artist) %></br>
		<%= link_to 'Delete', artist , method: :delete, data: { confirm: 'Are you sure?' } %> </br>
		<%= image_tag artist.image_path %> </br>

	<% end %>

app/views/artists/new.html.erb
<%= form_for(Artist.new) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :image_path %>
  <%= f.text_field :image_path %>

	<%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<%= link_to "All Artists", artists_path %>
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>